# CMI

environment: integration
destination: "../cmi-www/t/col"

sourceId: 17
cmiTitle: "Teachings of Christ Mind"
siteName: "Library of Christ Mind Teachings"

# Setup
title:        'Choose Only Love'
tagline:      'Now, we begin...'
description:  'Ścieżka przebudzenia dana przez Jeszuę w komunii z Jayemem (Jon Marc Hammer)'
url:          'https://www.christmind.info/t/col'
baseurl:      ''
keywords:     "Jesus, Jeshua, Channeled Material"
home:         "/t/col/"
port:         9917

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
semantic:     fui286
#semantic:     sui231
#semantic:     sui241
src-url:      'https://www.christmind.info/t/col'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

# Collections for transcripts
collections:
  acq:
    output: true
    title: Get Acquainted
  book1:
    output: true
    title: "Book 1: Echoes of Holiness"
  book2:
    output: true
    title: "Book 2: Let Yourself Be Loved"
  book3:
    output: true
    title: "Book 3: Homo-Christus Deo"
  book4:
    output: true
    title: "Book 4: Wisdom"

defaults:

  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/t/col/public/img/col/acq-big.jpg"
      image-width: 612
      image-height: 918
      bid: "acq"
      audio: false
      pnumToggle: false

  - scope:
      path: ""
      type: book1
    values:
      layout: transcript
      book: "Echoes of Holiness"
      publisher: "Choose Only Love"
      image: "/t/col/public/img/col/book1-big.jpg"
      image-width: 612
      image-height: 918
      bid: "book1"
      audio: false

  - scope:
      path: ""
      type: book2
    values:
      layout: transcript
      book: "Let Yourself Be Loved"
      publisher: "Choose Only Love"
      image: "/t/col/public/img/col/book2-big.jpg"
      image-width: 612
      image-height: 918
      bid: "book2"
      audio: false

  - scope:
      path: ""
      type: book3
    values:
      layout: transcript
      book: "Homo-Christus Deo"
      publisher: "Choose Only Love"
      image: "/t/col/public/img/tol/book3-big.jpg"
      image-width: 612
      image-height: 906
      bid: "book3"
      audio: false

  - scope:
      path: ""
      type: book4
    values:
      layout: transcript
      book: "Wisdom"
      publisher: "Choose Only Love"
      image: "/t/col/public/img/col/book4-big.jpg"
      image-width: 612
      image-height: 918
      bid: "book4"
      audio: false

exclude: [
  bin, standalone, moved.html, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

